// app/layout.js (Server Component)
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth/next";
import { authOptions } from "./api/auth/[...nextauth]/route"; // Correct import path
import SessionProvider from "../components/SessionProvider"; // Import the wrapper component

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // Fetch session server-side
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Wrap with Client-side SessionProviderWrapper */}
        <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  );
}
